#versao da sintaxe do docker-compose
version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=True
    ports:
      - 8000:8000
    volumes:
    - ./app:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
 dev-db-data:
